apiVersion: v1
kind: Secret
metadata:
  name: backend
type: Opaque
data:
  DATABASE_URL: bW9uZ29kYjovL3Jvb3Q6ZmlhcGdydXBvMjJAZGF0YWJhc2U6ODA=
  MERCADOPAGO_USERID: MTQwMjI1NTQ5
  MERCADOPAGO_TOKEN: VEVTVC02MTcxNzQ1ODE5MDE0NjYzLTA3MTkxOC1lM2Q4ZjE2ODAzMjFkZWFiNGE4YzBlNDMwYzIxMWRlMy0xNDAyMjU1NDk=
  MERCADOPAGO_POS: Mjc5Nw==
